name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored as a secret in GitHub
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored as a secret in GitHub

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .  # Context to your Dockerfile location
        push: true  # Push the image after building
        tags: yourdockerhubusername/your-repo-name:latest

  
    
